title: Appearances
subtitle: Players with at least {Min Matches} appearances who have played at least once since {Active since}
key: appearances
menu: Players
query_filters:
- desc: Min Matches
  default: 100
- desc: Active since
  default: 2000
columns:
- field: name
- field: from_yr
  heading: From
  class: year
- field: to_yr
  heading: To
  class: year
- field: seasons
  sort: hi
- field: appearances
  sort: hi
sql: >
    WITH player_lookup AS
    (
        SELECT id
        , surname || ', ' || COALESCE(firstname, initial, '') AS name
        FROM players
    )
    SELECT
      p.id
    , lkup.name
    , min(f.year) from_yr
    , max(f.year) to_yr
    , Count(*) seasons
    , Sum(f.matches) appearances
    FROM players p
        INNER JOIN performances f
        ON f.player_id = p.id
        INNER JOIN player_lookup lkup
        ON lkup.id = p.id
    GROUP BY
        p.id
    HAVING
        Sum(f.matches) >= $1
    AND Max(f.year) >= $2
    ORDER BY appearances DESC, from_yr
