title: Best Bowling
subtitle: All instances of 6 wickets or more, plus 5 or more since 2003
key: best_bowling
menu: Bowling
columns:
- field: name
  class: name
- field: wkts
  heading: Wickets
- field: runs
  heading: Runs
- field: opp
  heading: Opposition
  class: string
- field: date
  class: date
sql: >
      WITH player_lookup AS
      (
          SELECT id
          , surname || ', ' || COALESCE(firstname, initial, '') AS name
          FROM players
      )

      SELECT
        p.name
      , p.id
      , bb.date
      , bb.wkts
      , bb.runs
      , bb.opp
      FROM
        player_lookup p
          INNER JOIN
            best_bowlings bb ON bb.player_id = p.id
      ORDER BY
        bb.wkts DESC
      , bb.runs ASC
      , bb.date