title: Captains
menu: Players
columns:
- field: name
  heading: Name
  class: name
- field: from_yr
  heading: From
  class: year
- field: to_yr
  heading: To
  class: year
- field: seasons
  heading: Seasons
  sort: hi
- field: matches
  heading: Matches
  sort: hi
- field: won
  heading: Won
  sort: hi
- field: pct_won
  heading: Won %
  format: pct
  sort: hi
- field: lost
  heading: Lost
  sort: lo
- field: drawn
  heading: Drawn
  sort: lo
- field: tied
  heading: Tied
  sort: hi
- field: nodecision
  heading: N/D
  sort: hi
sql: >
    WITH player_lookup AS
    (
      SELECT id
      , surname || ', ' || COALESCE(firstname, initial, '') AS name
      FROM players
    )
    SELECT
      p.name
    , p.id
    , Min(c.year) from_yr
    , Max(c.year) to_yr
    , Count(*) seasons
    , Sum(c.matches) matches
    , Sum(c.won) won
    , Cast(Sum(c.won) AS REAL) / Sum(c.matches) * 100.0 pct_won
    , Sum(c.lost) lost
    , Sum(c.drawn) drawn
    , Sum(c.tied) tied
    , Sum(c.nodecision) nodecision
    FROM player_lookup p
      JOIN captains c
        ON c.player_id = p.id
    GROUP BY
      p.id
    , p.name
    ORDER BY
      matches DESC