title: Career Wickets
subtitle: Players with at least {Min Wickets} wickets
key: career_wickets
menu: Bowling
query_filters:
- desc: Min Wickets
  default: 10
columns:
- field: name
  heading: Name
  class: name
- field: from_yr
  heading: From
  class: year
- field: to_yr
  heading: To
  class: year
- field: seasons
  sort: hi
- field: wickets
  sort: hi
- field: runs
  sort: hi
- field: avg
  heading: Average
  format: 2dp
  sort: lo
- field: econ
  heading: Economy
  format: 2dp
  sort: lo
- field: strike_rate
  heading: Strike Rate
  format: 2dp
  sort: lo
sql: >
    WITH player_lookup AS
    (
        SELECT id
        , surname || ', ' || COALESCE(firstname, initial, '') AS name
        FROM players
    )
    SELECT
      p.id
    , lkup.name
    , Min(b.year) from_yr
    , Max(b.year) to_yr
    , Sum(CASE b.overs + b.balls WHEN 0 THEN 0 ELSE 1 END) seasons
    , Sum(b.wickets) wickets
    , Sum(b.runs) runs
    , CAST(Sum(b.runs) AS FLOAT) / Sum(b.wickets) avg
    , CAST(Sum(b.overs * 6 + b.balls) AS FLOAT) / Sum(b.wickets) strike_rate
    , Sum(runs) / CAST(Sum(b.overs * 6 + b.balls) AS FLOAT) * 6 econ
    FROM
      players p
        INNER JOIN
          performances b ON b.player_id = p.id
        INNER JOIN
          player_lookup lkup ON lkup.id = p.id
    GROUP BY
      p.id
    , lkup.name
    HAVING Sum(b.wickets) >= $1
    ORDER BY wickets DESC