title: "Player Performance: {player_name}"
subtitle: Season by season
key: performance
menu: false
parameters: {'player_id': 1}
columns:
- field: year
  class: year
- field: matches
- field: innings
- field: notout
  heading: Not Out
- field: high_score
  heading: Highest
- field: runsscored
  heading: Runs
- field: bat_avg
  heading: Average
  format: 2dp
- field: fours
- field: sixes
- field: overs
- field: maidens
- field: runs
- field: wickets
- field: bowl_avg
  heading: Average
  format: 2dp
- field: econ
  format: 2dp
- field: strike_rate
  heading: Strike Rate
  format: 2dp
- field: fivewktinn
  heading: Five-for+
- field: caught
- field: stumped
- field: fifties
- field: hundreds
- field: fives
- field: caughtwkt
  heading: Ct Wkt
- field: captain
- field: keptwicket
  heading: Kept Wkt
sql: >
        SELECT
          year
        , matches
        , innings
        , notout
        , highest || CASE WHEN highestnotout = 1 THEN '*' ELSE '' END high_score
        , runsscored
        , case innings
            WHEN notout THEN null
            ELSE CAST(runsscored AS FLOAT) / (innings - notout)
            END bat_avg
        , fours
        , sixes
        , (overs * 6 + balls) / 6 + ((overs * 6 + balls) % 6) / 10.0 overs
        , maidens
        , runs
        , wickets
        , CASE wickets
          WHEN 0 THEN NULL
          ELSE CAST(runs AS FLOAT) / wickets
          END bowl_avg
        , CASE wickets
          WHEN 0 THEN NULL
          ELSE CAST(overs * 6 + balls AS FLOAT) / wickets
          END strike_rate
        , runs / CAST(overs * 6 + balls AS FLOAT) * 6 econ
        , fivewktinn
        , caught
        , stumped
        , fifties
        , hundreds
        , fives
        , caughtwkt
        , captain
        , keptwicket
        FROM performances
        WHERE player_id = $1
        UNION
        SELECT
          'TOTAL'
        , Sum(matches)
        , Sum(innings)
        , Sum(notout)
        , (SELECT MAX(highest) FROM performances WHERE player_id = $1) ||
          CASE (
              SELECT Max(highestnotout)
              FROM performances
              WHERE player_id = $1
              AND highest = (
                  SELECT Max(highest)
                  FROM performances
                  WHERE player_id = $1)
          ) WHEN 1 THEN '*' ELSE '' END high_score
        , Sum(runsscored)
        , CASE Sum(innings)
          WHEN Sum(notout) THEN null
          ELSE CAST(Sum(runsscored) AS FLOAT) / (Sum(innings) - Sum(notout))
          END bat_avg
        , Sum(fours)
        , Sum(sixes)
        , Sum(overs * 6 + balls) / 6 + (Sum(overs * 6 + balls) % 6) / 10.0 overs
        , Sum(maidens)
        , Sum(runs)
        , Sum(wickets)
        , CASE Sum(wickets)
          WHEN 0 THEN NULL
          ELSE CAST(Sum(runs) AS FLOAT) / Sum(wickets)
          END bowl_avg
        , CASE Sum(wickets)
          WHEN 0 THEN NULL
          ELSE CAST(Sum(overs * 6 + balls) AS FLOAT) / Sum(wickets)
          END strike_rate
        , 6 * Sum(runs) / CAST(Sum(overs * 6 + balls) AS FLOAT) econ
        , Sum(fivewktinn)
        , Sum(caught)
        , Sum(stumped)
        , Sum(fifties)
        , Sum(hundreds)
        , Sum(fives)
        , Sum(caughtwkt)
        , Sum(captain)
        , Sum(keptwicket)
        FROM performances
        WHERE player_id = $1